// <auto-generated />
using System;
using L06HandsOnDB.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace L06HandsOnDB.Migrations
{
    [DbContext(typeof(AliensContext))]
    [Migration("20220224044728_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.2");

            modelBuilder.Entity("L06HandsOnDB.Alien", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Arms")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Heads")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Legs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlanetOfOrigin")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Aliens");
                });
#pragma warning restore 612, 618
        }
    }
}
